spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: restaurant_user
    password: restaurant_pw
  flyway:
    locations: classpath:/db/tables, classpath:/db/data
server:
  error:
    include-message: always